Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# セル直下に直接図示.
%matplotlib inline

# グラフおよびデザインに関するモジュール.
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

# air passenger データセット.
from sandbox.datasets import air_passengers

from sandbox.features.features import get_features                # 特徴量生成モジュール.
from sandbox.model_selection import (
    train_test_split,                                             # データ分割 (scikit-learn と同じ)
    GroupTimeSeriesSplit,                                         # 時系列用CV spliter
    XGBoostOptunaSearchCV                                         # CVを伴うXGBoost用ハイパーパラメータ探索
)
from sandbox.ensemble.boost import XGBoostRegressor               # XGBoost回帰器
from sandbox.metrics.score import mean_absolute_percentage_error  # MAPE(scikit-learn と同じ)

sns.set()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01msandbox[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdatasets[39;00m [38;5;28;01mimport[39;00m air_passengers
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01msandbox[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeatures[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfeatures[39;00m [38;5;28;01mimport[39;00m get_features                [38;5;66;03m# 特徴量生成モジュール.[39;00m
[0;32m---> 14[0m [38;5;28;01mfrom[39;00m [38;5;21;01msandbox[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m [38;5;28;01mimport[39;00m (
[1;32m     15[0m     train_test_split,                                             [38;5;66;03m# データ分割 (scikit-learn と同じ)[39;00m
[1;32m     16[0m     GroupTimeSeriesSplit,                                         [38;5;66;03m# 時系列用CV spliter[39;00m
[1;32m     17[0m     XGBoostOptunaSearchCV                                         [38;5;66;03m# CVを伴うXGBoost用ハイパーパラメータ探索[39;00m
[1;32m     18[0m )
[1;32m     19[0m [38;5;28;01mfrom[39;00m [38;5;21;01msandbox[39;00m[38;5;21;01m.[39;00m[38;5;21;01mensemble[39;00m[38;5;21;01m.[39;00m[38;5;21;01mboost[39;00m [38;5;28;01mimport[39;00m XGBoostRegressor               [38;5;66;03m# XGBoost回帰器[39;00m
[1;32m     20[0m [38;5;28;01mfrom[39;00m [38;5;21;01msandbox[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmetrics[39;00m[38;5;21;01m.[39;00m[38;5;21;01mscore[39;00m [38;5;28;01mimport[39;00m mean_absolute_percentage_error  [38;5;66;03m# MAPE(scikit-learn と同じ)[39;00m

File [0;32m/usr/local/lib/python3.10/site-packages/sandbox-0.0.0-py3.10.egg/sandbox/model_selection/__init__.py:2[0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m [38;5;124;03m""""""[39;00m
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_search[39;00m [38;5;28;01mimport[39;00m (
[1;32m      3[0m     BaseOptunaSearchCV,
[1;32m      4[0m     BaseOptunaStudyInitializer,
[1;32m      5[0m     LightGBMOptunaStepwiseSearchCV,
[1;32m      6[0m     XGBoostOptunaSearchCV,
[1;32m      7[0m )
[1;32m      8[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_split[39;00m [38;5;28;01mimport[39;00m (
[1;32m      9[0m     BaseCrossValidator,
[1;32m     10[0m     BaseShuffleSplit,
[0;32m   (...)[0m
[1;32m     30[0m     train_test_split,
[1;32m     31[0m )
[1;32m     33[0m __all__ [38;5;241m=[39m [
[1;32m     34[0m     [38;5;124m"[39m[38;5;124mBaseOptunaStudyInitializer[39m[38;5;124m"[39m,
[1;32m     35[0m     [38;5;124m"[39m[38;5;124mBaseOptunaSearchCV[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m     59[0m     [38;5;124m"[39m[38;5;124mtrain_test_split[39m[38;5;124m"[39m,
[1;32m     60[0m ]

File [0;32m/usr/local/lib/python3.10/site-packages/sandbox-0.0.0-py3.10.egg/sandbox/model_selection/_search.py:8[0m, in [0;36m<module>[0;34m[0m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mabc[39;00m [38;5;28;01mimport[39;00m abstractmethod
[1;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 8[0m [38;5;28;01mimport[39;00m [38;5;21;01moptuna[39;00m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjoblib[39;00m [38;5;28;01mimport[39;00m Parallel
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01moptuna[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlogging[39;00m [38;5;28;01mimport[39;00m DEBUG, ERROR, INFO, WARNING, set_verbosity

[0;31mModuleNotFoundError[0m: No module named 'optuna'
ModuleNotFoundError: No module named 'optuna'

